httpPort = 80

name = DB_FEWO_APP
host = 192.168.10.203
user = fewo_app
pass = 17126aa9-811a-4648-b17c-21a1c93f751f
jdbc = mariadb://{host=localhost}:{port=3306}/{name}?verifyServerCertificate=false&useSSL=false

dataroot = ./data-fewo

smtpHost = mx05.scheller.de
smtpPort = 587
smtpAuth = true
smtpTLS = true
smtpUser = fewo
smtpPass = SST2025@
senderEMail = fewo@scheller.de
#senderEMail = noreply@fewo.scheller.de

privatePages = chalets-in-nature.de
