httpPort = 8380

name = DB_FEWO
host = sql2
user = swe
pass = swe123
jdbc = mariadb://{host=localhost}:{port=3306}/{name}?verifyServerCertificate=false&useSSL=false

dataroot = ./data-fewo

smtpHost = mx04.scheller.de
smtpPort = 587
smtpAuth = true
smtpTLS = true
smtpUser = noreply@mobile4i.de
smtpPass = 2nFLnl9152DS
senderEMail = noreply@mobile4i.de
receiverEMail = d.solaiman@scheller.de

privatePages = chalets.local premier.local
publicPages = localhost fewo1.local fewo2.local fewobuchung.local fewo.scheller.de

outputSourceMaps = true
