#console.redirect = true # default true, redirect to logging
#console.output = false # default false, still output to sysout/syserr (could be done w/ logging)

#-------------------------------------------------------------------------------
# java.util.logging Settings
#

.level = ALL
sun.net.level = INFO
io.undertow.level = INFO
#de.scheller.level = ALL
#de.scheller.mwf.xio.level = INFO
#de.scheller.aface.vaadin.level = FINE
#de.scheller.system.cache.level = INFO
#de.scheller.platform.level = ALL
#de.scheller.platform.mdc.level = ALL
#de.scheller.storage.level = INFO
#de.scheller.plugin.level = FINE
# jnc.level = FINE causes calls to Thread.setName for each jnc call, can be slow
jnc.level = INFO
permissions.level = INFO
#de.scheller.mwf.Timing.level = FINE

#-------------------------------------------------------------------------------
# log4j Settings
#

org.apache.commons.logging.Log.allowFlawedHierarchy = true

#rootLogger.level = INFO
#rootLogger.level = DEBUG
rootLogger.level = ALL
rootLogger.appenderRef.stdout.ref = stdout
#rootLogger.appenderRef.mqtt.ref = mqtt
#rootLogger.appenderRef.rolling.ref = rolling
#rootLogger.appenderRef.logserver.ref = logserver
#rootLogger.appenderRef.xmllog.ref = xmllog

logger.sst.name = de.scheller
logger.sst.level = ALL
logger.jnc.name = jnc
logger.jnc.level = ALL
logger.sun.name = sun
logger.sun.level = INFO
logger.jmx.name = javax.management
logger.jmx.level = INFO
logger.jetty.name = org.eclipse.jetty
logger.jetty.level = INFO
logger.ehcache.name = net.sf.ehcache
logger.ehcache.level = INFO
logger.dbpool.name = com.zaxxer.hikari
logger.dbpool.level = INFO
logger.jsonpath.name = com.jayway.jsonpath
logger.jsonpath.level = INFO
logger.thymeleaf.name = org.thymeleaf
logger.thymeleaf.level = INFO
logger.mqtt.name = org.eclipse.paho
logger.mqtt.level = INFO
logger.mbeans.name = javax.management.mbeanserver
logger.mbeans.level = INFO
logger.webio.name = org.xnio
logger.webio.level = INFO
logger.web.name = io.undertow
logger.web.level = INFO
logger.webrequest.name = io.undertow.request
logger.webrequest.level = INFO
logger.webauth.name = io.undertow.request.security
logger.webauth.level = INFO
logger.proxy.name = io.undertow.server.handlers.proxy
logger.proxy.level = INFO
logger.proxy2.name = io.undertow.proxy
logger.proxy2.level = INFO
logger.webws.name = io.undertow.websockets
logger.webws.level = ALL
logger.orgws.name = org.java_websocket
logger.orgws.level = INFO
logger.vaadinws.name = org.atmosphere
logger.vaadinws.level = INFO
logger.vaadin.name = com.vaadin
logger.vaadin.level = INFO
logger.platform.name = de.scheller.platform
logger.platform.level = ALL
#logger.thymeleaf.name = org.thymeleaf
#logger.thymeleaf.level = DEBUG
#logger.thymeleafConfig.name = org.thymeleaf.TemplateEngine.CONFIG
#logger.thymeleafConfig.level = INFO

# uncomment these lines to log jnc in separate file
#logger.jnc.name = jnc
#logger.jnc.level = ALL
#logger.jnc.appenderRef.jnc.ref = jnc
#logger.jnc.additivity = false

# uncomment these lines to log memory stats in separate file
#logger.memstat.name = memstat
#logger.memstat.level = ALL
#logger.memstat.appenderRef.memstat.ref = memstat
#logger.memstat.additivity = false

appender.C.type = Console
appender.C.name = stdout
appender.C.filter.threshold.type = ThresholdFilter
appender.C.filter.threshold.level = ALL
appender.C.layout.type = PatternLayout
#appender.C.layout.pattern = %-5r %-5p [%t] %c %x - %m%n
#appender.C.layout.pattern = %-5r %-5p| %-25.25t | %15.15c | %m%n
#appender.C.layout.pattern = %d{yyMMdd HHmmss.SSS} %-5p| %20.20t | %20.20c | %X{session} %X{role} %X{user} | %m%n
appender.C.layout.pattern = %d{yyMMdd HHmmss.SSS} %-5p| %t | %c | %X{session} %X{role} %X{user} | %m%n

appender.R.type = RollingFile
appender.R.name = rolling
appender.R.fileName = logs/mwf-webapp.log
appender.R.filePattern = logs/mwf-webapp_%d{yyyyMMddHHmmss}-%i.log.gz
appender.R.policies.type = Policies
appender.R.policies.startup.type = OnStartupTriggeringPolicy
appender.R.policies.cron.type = CronTriggeringPolicy
appender.R.policies.cron.schedule = 0 0 0 * * ?
appender.R.policies.size.type = SizeBasedTriggeringPolicy
appender.R.policies.size.size = 500MB
appender.R.strategy.type = DefaultRolloverStrategy
appender.R.strategy.min = 1
appender.R.strategy.max = 5
appender.R.strategy.fileIndex = 1
appender.R.filter.threshold.type = ThresholdFilter
appender.R.filter.threshold.level = ALL
appender.R.layout.type = PatternLayout
#appender.R.layout.pattern = %d{yyMMdd HHmmss.SSS} %-5p| %20.20t | %20.20c | %X{session} %X{role} %X{user} | %m%n
appender.R.layout.pattern = %d{yyMMdd HHmmss.SSS} %-5p| %t | %c | %X{session} %X{role} %X{user} | %m%n

appender.J.name = jnc
appender.J.type = File
appender.J.fileName = logs/webapp-jnc.log
appender.J.append = false
appender.J.layout.type = PatternLayout
appender.J.layout.pattern = %d{MMdd HHmmss} %-5p| %m%n

appender.M.name = memstat
appender.M.type = File
appender.M.fileName = logs/webapp-memstat.log
appender.M.append = false
appender.M.layout.type = PatternLayout
appender.M.layout.pattern = %d{MMdd HHmmss} %-5p| %m%n

#appender.S.name = logserver
#appender.S.type = Socket
#appender.S.host = 192.168.10.236
#appender.S.port = 4560
#appender.S.layout.type = JsonLayout

#appender.X.name = xmllog
#appender.X.type = File
#appender.X.fileName = logs/serverlog.xml
#appender.X.layout.type = XMLLayout
#appender.X.append = false

#appender.R.name = rolling
#appender.R.type = RollingFile
#appender.R.fileName = logs/serverlog.log
#appender.R.layout = PatternLayout
#appender.R.layout.pattern = %-4r [%t] %-5p %c %x - %m%n

packages = de.scheller.platform.network.log

#appender.MQTT.name = mqtt
#appender.MQTT.type = MqttAppender
# if not defined, PLATFORM_BUS is used
#appender.MQTT.broker = tcp://swe03
#appender.MQTT.username = username
#appender.MQTT.password = password
#appender.MQTT.topic = de.scheller.platform/{realm}/{host}/log/{node}/{proc}
#appender.MQTT.clientid=clientid_{host}_{node}_{proc}
